### Get all activity
GET http://localhost:6050/activity

### Create activity
POST http://localhost:6050/activity
Content-Type: application/json

{
    "activityName":      		"Hil chao",
	"description": 	"Find friends to eat dinner together.",
	"imageProfile":	"www.img.co/dummy.img",
	"activityType":			["restaurant","GG"],
	"ownerId": 		"a92dikjsiao92nfaoiw",
	"location":		"Siam park",
	"maxParticipant":	15,
	"participant":   ["a92dikjsiao92nfaoiw"],
	"date":			"2510-04-04T07:00:00.000Z",
	"duration":		"3 hours",
	"chatId":			"09jdao92ndnawndsak"
}


### get activity
GET http://localhost:6050/activity/63305b338cf996e6512f2990

### Edit activity
PUT http://localhost:6050/activity/63305b338cf996e6512f2990
Content-Type: application/json

{
    "activityName":      		"Hil chao",
	"description": 	"Find friends to eat dinner together.",
	"imageProfile":	"www.img.co/dummy.img",
	"activityType":			["restaurant","GG"],
	"ownerId": 		"a92dikjsiao92nfaoiw",
	"location":		"Siam park",
	"maxParticipant":	15,
	"participant":   ["a92dikjsiao92nfaoiw"],
	"date":			"2510-04-04T07:00:00.000Z",
	"duration":		"3 hours and  a half",
	"chatId":			"09jdao92ndnawndsak"
}

### Get activity
DELETE  http://localhost:6050/activity/633059894cb26b465ec24a46